In [3]:
name=input("enter your name")
age=int(input("enter you age "))
height=float(input("enter your height"))
print("my name is ",name,"my age is",age,"my height is ",height)



ValueError: invalid literal for int() with base 10: ''

ValueError: invalid literal for int() with base 10: 'enter number'

In [14]:
num1=int(input("enter number"))

num2=int(input("enter number"))

num3=int(input("enter number"))
sum=(num1+num2+num3)/3
print(sum)

2.3333333333333335


In [15]:
print(-8%3)

1


In [16]:
age=int(input("enter your age"))
if age>18:
    print ("you can vote")
else:
    print ("you cant vote")



you can vote


In [1]:
side1=int(input("enter the first side"))
side2=int(input("enter the 2nd side "))
side3=int(input("enter the 3rd side "))

if side1==side2 && side2==side3
print("e")
elif side1==side2 or side2=side3 or side3==side1:
print("I")
else:
print("s") 



SyntaxError: invalid syntax (2158624529.py, line 5)

In [3]:
for i in range(1,11):
print(i)

IndentationError: expected an indented block after 'for' statement on line 1 (1310101218.py, line 2)

In [19]:
list=[1,3,5,2,7,5,11,14,12]
x = len(list)//2
print[list[x]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [20]:
lst=[1,2,3,4,5,6,7,8,]
print(lst[-2:-9:-3])

[7, 4, 1]


In [21]:
lst=[1,2,3,4,5,6,7,8,]
print(lst[-2:-9:-3])

[7, 3, 2]


In [22]:
lst=[1,2,3,4,5,6,7,8,]
print(lst[::3])

[1, 4, 7]


In [24]:
lst=[12,24,32,49,6,7,8]
for i in range (len(lst)):
    print(lst[i],end=" ")

12 24 32 49 6 7 8 

In [25]:
!pip3 install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 320.0 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 806.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
    --------------------------------------- 0.2/15.5 MB 5.9 MB/s eta 0:00:03
   - -------------------------------------- 0.6/15.5 MB 7.9 MB/s eta 0:00:02
   -- ------------------------------------- 1.1/15.5 MB 8.8 MB/s eta 0:00:02
   ----- ---------------------------------- 2.2/15.5 MB 14.0 MB/s eta 0:00:01
   ---------- ----------------------------- 3.9/15.5 MB 17.7 MB/s eta 0:00:01
   -------------- ------------------------- 5.6/15.5 MB 22.3 MB/s eta 0:00:01
   ----------------- ---------------------- 6.8/15.5 MB 21.7 MB/s eta 0:00:01
   ---------------------- ----------------- 8.5/15.5 MB 23.7 MB/s eta 0:00:01
   -------------------------- ------------- 10.1/15.5 MB 25.9 MB/s eta 0:00:0

In [26]:
import numpy as np



In [ ]:
# prinyt dimentions 
a.ndim

In [ ]:
#print shape
print(a.shape)

In [4]:
import numpy as np

a = np.diag([1,2,3,4])  # Removed the extra comma
print(a)
print(a[1,2])  # Accessing the element at row 1, column 2

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
0
